matrix:
  include:
    - language: java
      jdk: 
        - oraclejdk8
      services:
        - postgresql
      addons:
        sonarcloud:
          organization: "ftn-kts-nvt-2020"
          token:
            secure: "QsS7ncXm65nk6yVlkdwHZs6jAE4GGwpUuQ6hhskMYotPIIUzgCN7ABTKdWXIOvv+s8dLT5wyS7Gg9UaKjIgFCXWVQK4NLo9R00779ZFMyneiU4mjY4vQlp9UwKxhCx0wcLZpUAUOGamKvb7AbbZiT1s/JFift4yXCSoSth2L82N8yjrv2YuU78JRggzg0ejZu/xnYgTKa9HgNnFHpjTkcCz53/KaCIOIZ7c2RP+rnAmcra7N4tbJtb1TCoz2mzK9dLKx7thkesOXYEWcHgAP+QFlNlY/eNVtxC6cNeUygJfVzjZEf1q39b5mCcQteMQY9Q2l5d4tRZVFT3xpn4fId/pGeICSu6RTQHTI8qFY7OraUPcdzAnf4s/OrWhFNmsIrTpGuwrsjxol/f7X5VR1MeFzlbEUM/jGojvvi8Jv8U9NbHdc8BRGTNf8eAIvkB6BS0WKF/Vmlq80HnqP9HOF138ImorOGsT1NC2HCbw02GQDlSUc5jJuEwrEJB+TMTXSk3ZP58z7lquwUvKefxpiHwHICBQ0QmW3+6lT0CzuTe53hReZ69yOemUUP42tZlfCQkPywWvN3DKRUoOkcbIfkukVQEoOy/kyx8XzlU4IbctliAncNsnXN5Oew7NYsemoSQ2KXVAqp4KwhUgvNKVF/6llATItEUWEt+ESVhpvdJ8="
      before_script:
        - psql -c 'create database cultism;' -U postgres
      before_install:
        - cd backend
      install:
        - mvn -N io.takari:maven:wrapper
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - ./mvnw clean install
        - ./mvnw clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=phuskus_kulturna-ponuda
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself-api
        on: main

    - language: node_js
      node_js: 
        - node
      addons:
        sonarcloud:
          organization: "ftn-kts-nvt-2020"
          token:
            secure: "QsS7ncXm65nk6yVlkdwHZs6jAE4GGwpUuQ6hhskMYotPIIUzgCN7ABTKdWXIOvv+s8dLT5wyS7Gg9UaKjIgFCXWVQK4NLo9R00779ZFMyneiU4mjY4vQlp9UwKxhCx0wcLZpUAUOGamKvb7AbbZiT1s/JFift4yXCSoSth2L82N8yjrv2YuU78JRggzg0ejZu/xnYgTKa9HgNnFHpjTkcCz53/KaCIOIZ7c2RP+rnAmcra7N4tbJtb1TCoz2mzK9dLKx7thkesOXYEWcHgAP+QFlNlY/eNVtxC6cNeUygJfVzjZEf1q39b5mCcQteMQY9Q2l5d4tRZVFT3xpn4fId/pGeICSu6RTQHTI8qFY7OraUPcdzAnf4s/OrWhFNmsIrTpGuwrsjxol/f7X5VR1MeFzlbEUM/jGojvvi8Jv8U9NbHdc8BRGTNf8eAIvkB6BS0WKF/Vmlq80HnqP9HOF138ImorOGsT1NC2HCbw02GQDlSUc5jJuEwrEJB+TMTXSk3ZP58z7lquwUvKefxpiHwHICBQ0QmW3+6lT0CzuTe53hReZ69yOemUUP42tZlfCQkPywWvN3DKRUoOkcbIfkukVQEoOy/kyx8XzlU4IbctliAncNsnXN5Oew7NYsemoSQ2KXVAqp4KwhUgvNKVF/6llATItEUWEt+ESVhpvdJ8="
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build
        - sonar-scanner
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself
        on: main

dist: trusty


  
notifications:
  email: 
    - mariokipoki@gmail.com