matrix:
  include:
    - language: java
      jdk: 
        - oraclejdk8
      services:
        - postgresql
      addons:
        sonarcloud:
          organization: "ftn-kts-nvt-2020"
          token:
            secure: "m8TcvTXt21+EIckr6PVLk3uHF3qX/nx0sxOm7x09k75eMA+loRFy91IsqaW6hgFquehI3CaF+2jkTbEV7Qp5rONsjbjxcvgUIAnoMxlTxJ3YqIuul9hda0sf264HTVBwkvVXgZdQgq301VIEcLKC6T+GqNxBcKtTQNQ9g4HPiJwRLY0TLU/yU+qJy/b321wqsyKFZrYtHeDxEAozovDHonFzU6N2dCtY4CQW+Oj1HvML+ygRugVKYMplZhUvJZwaif91mD8sR3DPWjXWRFUGMQHm9v4nxb+DmHztk1uNeWQFk+vtd6PH1Ji1OuPmDwLit1xHtkL2Hbr988KrquU6lmvG3SwojILFXTfh013xgb1uEDasFXbDCAXIDcFBeoFj4eUoah91cbqrhE5FN5kmnifFc7srzVcc2wcIRyw2T0QktTAWLeZ/kYYEKAgwSfv4zZhtdcxieeMqZL+KuOsOrTSYuinW+iN4orGIRx0KorHwrIVYffUp6CSRly5gODIHZju0C159lQEbfJOEWdNCevOKNkdodKlukX9TIiNzHtokf9SYIu9wZhBUTHdOTg7idX/sntbCdZ70QghJwmXVwq/8JxMg74g3mzH+8Jlc7clNcjaGXBL7vomaqR6org0qrpMw8nC526//8UWU5BjIDYmyidFqGQLLtln0e80PPNY="
      before_script:
        - psql -c 'create database cultism;' -U postgres
      before_install:
        - cd backend
      install:
        - mvn -N io.takari:maven:wrapper
        - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
      script:
        - ./mvnw clean install
        - ./mvnw clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=phuskus_kulturna-ponuda -Dsonar.login=c1b10c9e696ea3f68a99b4d2ccc990806f9cb8e0
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself-api
        on: main

    - language: node_js
      node_js: 
        - node
      addons:
        sonarcloud:
          organization: "ftn-kts-nvt-2020"
          token:
            secure: "m8TcvTXt21+EIckr6PVLk3uHF3qX/nx0sxOm7x09k75eMA+loRFy91IsqaW6hgFquehI3CaF+2jkTbEV7Qp5rONsjbjxcvgUIAnoMxlTxJ3YqIuul9hda0sf264HTVBwkvVXgZdQgq301VIEcLKC6T+GqNxBcKtTQNQ9g4HPiJwRLY0TLU/yU+qJy/b321wqsyKFZrYtHeDxEAozovDHonFzU6N2dCtY4CQW+Oj1HvML+ygRugVKYMplZhUvJZwaif91mD8sR3DPWjXWRFUGMQHm9v4nxb+DmHztk1uNeWQFk+vtd6PH1Ji1OuPmDwLit1xHtkL2Hbr988KrquU6lmvG3SwojILFXTfh013xgb1uEDasFXbDCAXIDcFBeoFj4eUoah91cbqrhE5FN5kmnifFc7srzVcc2wcIRyw2T0QktTAWLeZ/kYYEKAgwSfv4zZhtdcxieeMqZL+KuOsOrTSYuinW+iN4orGIRx0KorHwrIVYffUp6CSRly5gODIHZju0C159lQEbfJOEWdNCevOKNkdodKlukX9TIiNzHtokf9SYIu9wZhBUTHdOTg7idX/sntbCdZ70QghJwmXVwq/8JxMg74g3mzH+8Jlc7clNcjaGXBL7vomaqR6org0qrpMw8nC526//8UWU5BjIDYmyidFqGQLLtln0e80PPNY="
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build
        - cd ..
        - sonar-scanner -X
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself
        on: main

dist: trusty


  
notifications:
  email: 
    - mariokipoki@gmail.com