matrix:
  include:
    - language: java
      jdk: 
        - oraclejdk8
      services:
        - postgresql
      before_script:
        - psql -c 'create database cultism;' -U postgres
      before_install:
        - cd backend
      install:
        - mvn -N io.takari:maven:wrapper
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself-api
        on: main

    - language: node_js
      node_js: 
        - node
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build
      deploy:
        provider: heroku
        api_key: 5f905c71-937c-47a5-b3f2-7611aa2dd7c1
        app: cult-yourself
        on: main

dist: trusty


notifications:
  email: 
    - mariokipoki@gmail.com